services:
  docker-container-update:
    image: npcdw/docker-container-update
    container_name: docker-container-update
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/local/soft:/usr/local/soft"
      # 定时任务日志目录，跟着重启也能留档
      - "./logs:/var/log/docker-container-update"
    environment:
      TZ: 'Asia/Shanghai'
      LANG: 'C.UTF-8'
      LC_ALL: 'C.UTF-8'